# try:
#     numerator = 10
#     denominator = 5
     
#     result = numerator/denominator
    
#     print(result)
# except:
#     print("error:denomimator cannot be 0.")
    
# try:
#     numerator = 10
#     denominator = 0
     
#     result = numerator/denominator
    
#     print(result)
# except:
#     print("error:denomimator cannot be 0.")

# try:
#     print(x)
# except:
#     print("an exception occured")

# try:
#   print("hello")
# except:
#   print("something went wrong")
# else:
#   print("nothing went wrong")

# try:
#   print(x)
# except:
#   print("something went wrong")
# finally:
#   print("The 'try except' is finished")

